on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Config
    steps:
      - name: Build Config
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: firmware
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
