on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: firmware.zip
      - name: Checkout code
        uses: actions/checkout@v2
      - name: tree
        run: find | sed 's|[^/]*/|- |g'
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: >-
          gh release create ${{ github.ref_name }}
          "firmware.zip"
          --generate-notes
          --title "Version ${{ github.ref_name }}"
