on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: firmware.zip
          token: ${{ secrets.GH_TOKEN }}