on: [push]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get current datetime
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d._%H.%M.%S')"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware
      - name: tree
        run: ls -R
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: >-
          gh release create v0.${{ github.run_id }}
          "/home/runner/work/zmk-config/zmk-config/lily58_left-nice_nano_v2-zmk.uf2"
          "/home/runner/work/zmk-config/zmk-config/lily58_right-nice_nano_v2-zmk.uf2"
          --notes "${{ github.event.head_commit.message}}"
          --title "v0.${{ github.run_id }}"
